name: CI - Build et Tests

on:
  push:
    branches: [main, develop, feat/seo-core-fixes]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.11.1
        run_install: false
    
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Run linter
      run: pnpm lint
    
    - name: Run tests avec couverture
      run: pnpm test:coverage
      env:
        CI: true
    
    - name: Build application
      run: pnpm build
      env:
        CI: true
    
    - name: Vérifier la génération du sitemap
      run: |
        if [ ! -f "public/sitemap.xml" ]; then
          echo "❌ Erreur: sitemap.xml non généré"
          exit 1
        fi
        echo "✅ sitemap.xml généré avec succès"
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-reports
        path: coverage/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-output
        path: |
          .next/
          public/sitemap.xml
          public/robots.txt